version: '3.7'
services:
  db1:
    image: postgres:12.3-alpine
    ports:
      - 5410:5432
    restart: always
    environment:
        - POSTGRES_PASSWORD=pass
        - POSTGRES_USER=app
        - POSTGRES_DB=DB
    volumes:
      - ./docker-entrypoint-initdb.d/01_db1:/docker-entrypoint-initdb.d:ro
  db2:
    image: postgres:12.3-alpine
    ports:
      - 5411:5432
    restart: always
    environment:
          - POSTGRES_PASSWORD=pass
          - POSTGRES_USER=app
          - POSTGRES_DB=DB
    volumes:
      - ./docker-entrypoint-initdb.d/01_db2:/docker-entrypoint-initdb.d:ro
  db3:
    image: postgres:12.3-alpine
    ports:
      - 5412:5432
    restart: always
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=app
      - POSTGRES_DB=DB
    volumes:
      - ./docker-entrypoint-initdb.d/01_db3:/docker-entrypoint-initdb.d:ro